### ISSUE TITLE
Liquids & blocks that can rotate do not fade correctly

### ISSUE THREAD

**Issue by RaderRMT** [onnowhere/core_shaders#1]
I don't know if you really want issues on this, and i'm sure you're aware of those issues, but i'll make one anyway :)

I'm using the latest version (1.0.2 as of writing this) (used on the debug world) (I'm sure I haven't spotted everything, but that's what i saw first):

- Water (and water in waterlogged blocks) & lava do not fade correctly, same thing for most blocks that can rotate (except from stairs, walls, fences, fence gates)

![image](https://user-images.githubusercontent.com/41066767/112731248-5874fd00-8f36-11eb-93b7-f055dd295be6.png)

- Blocks that can rotate, such as logs, dispensers, rods, chains, etc.. do not fade correctly too

![image](https://user-images.githubusercontent.com/41066767/112731262-73477180-8f36-11eb-8570-53e6fba629ea.png)

- Banners will turn white (and keep their original color too) when near the distance threshold

![Screenshot](https://user-images.githubusercontent.com/41066767/112731182-0b912680-8f36-11eb-9b9f-b49121e8e9fc.png)

- "X" shaped blocks (such as ferns, grass, cobwebs) do not fade correctly
- Some waterloggable blocks (such as the new dripleaf) do not fade correctly
- Mobs do not fade correctly

**Comment by onnowhere** [comment]
No problem, thanks for the issue!
- Blocks with rotation and/or mirroring in random variants fixed in 1.0.3

Remaining issues likely cannot be fixed due to lack of information in vanilla core shaders (this includes issues with liquids, blocks with rotated faces at non-90 degree angles, and entities)

https://github.com/onnowhere/core_shaders/releases/tag/1.0.3
