### ISSUE TITLE
Beds and piston head do not face correctly

### ISSUE THREAD

**Issue by RaderRMT** [onnowhere/core_shaders#2]
Using the latest version (1.0.3), beds are not fading correctly:
![bed](https://user-images.githubusercontent.com/41066767/112814960-1bb51d00-9080-11eb-95ff-cb429a73225e.png)

Piston heads to not fade correctly too (it's worse when they move)
![piston head](https://user-images.githubusercontent.com/41066767/112816657-ec071480-9081-11eb-9ae6-7d35ee0c8e67.png)
Video of a piston moving when fading: https://youtu.be/Mvue6cWZUwc

I have not included blocks with faces at non-90° angles (banners, signs, torches, lecterns, ferns, etc...), entities & liquids
(Banners now keep their color, but they still don't face correctly because they fall in the "blocks with faces at non-90° angles" category)
Chests and shulker boxes do not fade correctly, maybe because they fall in the "blocks with faces at non-90° angles" category when the player opens them

**Comment by onnowhere** [comment]
Unfortunately these also cannot be fixed right now due to these blocks actually falling in one of the entity rendertypes. For example, beds are rendered as `rendertype_entity_solid`, which means it's not possible to reliably figure out which corner of a face is where relative to the center of the face. Thank you for the post though!
